### ISSUE TITLE
Optimizer error 'str' object has no attribute 'name' on `get_field_def`

### ISSUE THREAD

**Issue by lautarodapin-magoya** [tfoxy/graphene-django-optimizer#93]
This is the info context
```py
GraphQLResolveInfo(field_name='childOrganizations', field_nodes=[FieldNode at 39:70], return_type=<GraphQLNonNull <GraphQLList <GraphQLNonNull <GrapheneObjectType 'OrganizationType'>>>>, parent_type=<GrapheneObjectType 'Query'>, path=Path(prev=None, key='childOrganizations', typename='Query'), schema=<graphql.type.schema.GraphQLSchema object at 0x7ff2eebc0650>, fragments={}, root_value=None, operation=OperationDefinitionNode at 0:72, variable_values={}, context=<WSGIRequest: POST '/graphql/'>, is_awaitable=<function assume_not_awaitable at 0x7ff2f18f22a0>)
Using selector: EpollSelector
```

And i'm getting the error when the optimizer tries to get the field def
```py

field_def = get_field_def(info.schema, info.parent_type, info.field_name)
```
and it gets the error in the first linne of the function due to `field_node` is now a string
```py
def get_field_def(
        schema: GraphQLSchema, parent_type: GraphQLObjectType, field_node: FieldNode
) -> GraphQLField:
        """Get field definition.

    This method looks up the field on the given type definition. It has special casing
    for the three introspection fields, ``__schema``, ``__type`, and ``__typename``.
    ``__typename`` is special because it can always be queried as a field, even in
    situations where no other fields are allowed, like on a Union. ``__schema`` and
    ``__type`` could get automatically added to the query type, but that would require
    mutating type definitions, which would cause issues.

    For internal use only.
    """
    field_name = field_node.name.value

    if field_name == "__schema" and schema.query_type == parent_type:
            return SchemaMetaFieldDef
    elif field_name == "__type" and schema.query_type == parent_type:
            return TypeMetaFieldDef
    elif field_name == "__typename":
            return TypeNameMetaFieldDef
    return parent_type.fields.get(field_name)

```
```py
ipdb> info.field_name.name.value
*** AttributeError: 'str' object has no attribute 'name'
Using selector: EpollSelector
```

```toml
[tool.poetry]
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.3"
graphene = "^3.2.2"
graphene-django = "^3.1.2"
graphene-file-upload = "^1.3.0"
pillow = "^10.0.0"
sentry-sdk = "^1.27.0"
rq = "^1.15.1"
django-admin-interface = "^0.26.0"
django-modeladmin-reorder = "^0.3.1"
django-anymail = "^10.0"
django-extensions = "^3.2.3"
django-rq = "^2.8.1"
django-import-export = "^3.2.0"
django-mptt = "^0.14.0"
django-solo = "^2.1.0"
django-simple-history = "^3.3.0"
django-tinymce = "^3.6.1"
psycopg2-binary = "^2.9.6"
django-model-utils = "^4.3.1"
django-redis = "^5.3.0"
hiredis = "^2.2.3"
graphene-django-optimizer = "^0.9.1"

[tool.poetry.dev-dependencies]
ipython = "^8.14.0"
ipdb = "^0.13.13"


[build-system]
requires = ["poetry>=1.5.1"]
build-backend = "poetry.masonry.api"
```
